CREATE TABLE enrollments_risk_signals
(
    reference_id                     SERIAL PRIMARY KEY NOT NULL,
    enrollment_id                    text UNIQUE,
    device_id                        varchar,
    is_rooted_device                 boolean,
    screen_brightness               double precision,
    elapsed_time_since_boot         integer,
    os_version                      varchar,
    user_time_zone_offset           varchar,
    language                        varchar,
    screen_dimensions_height        varchar,
    screen_dimensions_width         varchar,
    account_tenure                  date,
    geolocation_latitude            double precision,
    geolocation_longitude           double precision,
    geolocation_type                varchar,
    is_call_in_progress             boolean,
    is_dev_mode_enabled             boolean,
    is_mock_gps                     boolean,
    is_emulated                     boolean,
    is_monkey_runner                boolean,
    is_charging                     boolean,
    antenna_information             varchar,
    is_usb_connected                boolean,
    integrity_app_recognition_verdict varchar,
    integrity_device_recognition_verdict varchar,
    created_at                      date,
    created_by                      varchar(20),
    updated_at                      date,
    updated_by                      varchar(20),
    hibernate_status                varchar,
    FOREIGN KEY (enrollment_id) REFERENCES enrollments (enrollment_id) ON DELETE CASCADE
);

CREATE TABLE enrollments_risk_signals_aud
(
    reference_id                     SERIAL PRIMARY KEY NOT NULL,
    enrollment_id                    text UNIQUE,
    device_id                        varchar,
    is_rooted_device                 boolean,
    screen_brightness               double precision,
    elapsed_time_since_boot         integer,
    os_version                      varchar,
    user_time_zone_offset           varchar,
    language                        varchar,
    screen_dimensions_height        varchar,
    screen_dimensions_width         varchar,
    account_tenure                  date,
    geolocation_latitude            double precision,
    geolocation_longitude           double precision,
    geolocation_type                varchar,
    is_call_in_progress             boolean,
    is_dev_mode_enabled             boolean,
    is_mock_gps                     boolean,
    is_emulated                     boolean,
    is_monkey_runner                boolean,
    is_charging                     boolean,
    antenna_information             varchar,
    is_usb_connected                boolean,
    integrity_app_recognition_verdict varchar,
    integrity_device_recognition_verdict varchar,
    created_at                      date,
    created_by                      varchar(20),
    updated_at                      date,
    updated_by                      varchar(20),
    hibernate_status                varchar,
    rev                             integer NOT NULL,
    revtype                         smallint,
    FOREIGN KEY (rev) REFERENCES revinfo (rev)
);