CREATE TABLE "account_transactions"(
    "account_transaction_id" SERIAL PRIMARY KEY NOT NULL,
    "account_id" uuid NOT NULL,
    "transaction_id" varchar,
    "completed_authorised_payment_type" varchar,
    "credit_debit_type" varchar,
    "transaction_name" varchar,
    "type" varchar,
    "amount" float8,
    "transaction_currency" varchar,
    "transaction_date" date,
    "partie_cnpj_cpf" varchar,
    "partie_person_type" varchar,
    "partie_compe_code" varchar,
    "partie_branch_code" varchar,
    "partie_number" varchar,
    "partie_check_digit" varchar,
    "created_at" timestamp,
    "updated_at" timestamp,
    "hibernate_status" varchar,
    "created_by" varchar,
    "updated_by" varchar,
    FOREIGN KEY (account_id) REFERENCES "accounts" (account_id)
);

CREATE TABLE "account_transactions_aud"(
    "account_transaction_id" integer NOT NULL,
    "account_id" uuid,
    "transaction_id" varchar,
    "completed_authorised_payment_type" varchar,
    "credit_debit_type" varchar,
    "transaction_name" varchar,
    "type" varchar,
    "amount" float8,
    "transaction_currency" varchar,
    "transaction_date" date,
    "partie_cnpj_cpf" varchar,
    "partie_person_type" varchar,
    "partie_compe_code" varchar,
    "partie_branch_code" varchar,
    "partie_number" varchar,
    "partie_check_digit" varchar,
    "created_at" timestamp,
    "updated_at" timestamp,
    "hibernate_status" varchar,
    "created_by" varchar,
    "updated_by" varchar,
    "rev" int4 NOT NULL,
    "revtype" int2,
    PRIMARY KEY ("account_transaction_id", "rev"),
    FOREIGN KEY ("rev") REFERENCES "revinfo" ("rev")
);
