package com.raidiam.trustframework.bank;

import com.raidiam.trustframework.mockbank.models.generated.*;
import io.micronaut.core.annotation.Introspected;
import org.hibernate.envers.DefaultRevisionEntity;

import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.Map;

@Introspected(classes = {
        BusinessEntity.class,
        BusinessEntityDocument.class,
        CreateConsent.class,
        CreateConsentData.class,
        CreateConsentV2.class,
        CreateConsentV2Data.class,
        Links.class,
        LoggedUser.class,
        Meta.class,
        ResponseConsent.class,
        ResponseConsentFull.class,
        ResponseConsentData.class,
        ResponseConsentFullData.class,
        ResponseError.class,
        ResponseErrorErrors.class,
        OffsetDateTime.class,
        UpdateConsent.class,
        UpdateConsentData.class,
        String.class,
        DefaultRevisionEntity.class,
        Map.class,
        CreatePixPayment.class,
        CreatePixPaymentData.class,
        CreatePixPaymentV2.class,
        CreatePixPaymentDataV2.class,
        EnumLocalInstrument.class,
        PaymentPix.class,
        CreditorAccount.class,
        EnumAccountPaymentsType.class,
        UpdatePixPayment.class,
        UpdatePixPaymentData.class,
        EnumPaymentStatusType.class,
        CreatePaymentConsent.class,
        CreatePaymentConsentData.class,
        CreatePaymentConsentV4.class,
        CreatePaymentConsentV4Data.class,
        CreateConsentExtends.class,
        CreateConsentExtendsData.class,
        ResponseConsentReadExtends.class,
        ResponseConsentReadExtendsData.class,
        Identification.class,
        PaymentConsent.class,
        DebtorAccount.class,
        UpdatePixPaymentV2.class,
        UpdatePixPaymentDataV2.class,
        UpdatePaymentConsent.class,
        UpdatePaymentConsentData.class,
        EnumAuthorisationFlow.class,
        PatchPaymentsV2.class,
        PatchPaymentsDataV2.class,
        CreatePixPaymentV3.class,
        CreatePixPaymentDataV3.class,
        CreatePixPaymentV4.class,
        CreatePixPaymentDataV4.class,
        PatchPixPaymentV4.class,
        PatchPixPaymentV4Data.class,
        CreateEnrollment.class,
        PatchEnrollment.class,
        UpdateEnrollment.class,
        CreateConsentData.class,
        ResponseCreateEnrollment.class,
        EnrollmentFidoRegistration.class,
        EnrollmentFidoRegistrationData.class,
        RiskSignals.class,
        RiskSignalsPayments.class,
        EnrollmentFidoOptionsInput.class,
        EnrollmentFidoSignOptionsInput.class,
        ConsentAuthorization.class,
        ConsentAuthorizationData.class,
        ScheduleSingleSingle.class,
        CreateRecurringConsentV1.class,
        CreateRecurringConsentV1Data.class,
        PatchRecurringConsentV1.class,
        PatchRecurringConsentV1Data.class,
        RecurringConsentRejectionV1.class,
        RecurringConsentRevocationV1.class,
        CreateConsentV3.class,
        CreateConsentV3Data.class,
        CreateConsentExtendsV3.class,
        CreateConsentExtendsV3Data.class,
        CreateRecurringPixPaymentV1.class,
        CreateRecurringPixPaymentV1Data.class,
        LocalDate.class,
        Schedule.class,
        Single.class,
        RecurringPatchPixPayment.class,
        RecurringPatchPixPaymentData.class,
        RiskSignalsPaymentsAutomatic.class,
        RiskSignalsPaymentsManual.class,
        RiskSignalsConsentsIntegrity.class,
        RiskSignalsConsentsGeolocation.class,
        RiskSignalsConsentsScreenDimensions.class
})
public class SwaggerIntrospectionConfig {
}
